const quotes = [
"The journey of a thousand miles begins with one step",
"That which does not kill us makes us stronger",
"Fortune favors the bold",
"Life is what happens when you’re busy making other plans",
"When the going gets tough the tough get going",
"You must be the change you wish to see in the world",
"You only live once but if you do it right once is enough",
"I think therefore I am",
"Tough times never last but tough people do",
"Get busy living or get busy dying",
"Whether you think you can or you think you can’t you’re right",
"Tis better to have loved and lost than to have never loved at all",
"Time is money",
"A man is but what he knows",
"You miss 100 percent of the shots you never take",
"If you’re going through hell keep going",
"Strive not to be a success but rather to be of value",
"I came I saw I conquered",
"Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do",
"Great minds discuss ideas average minds discuss events small minds discuss people",
"Those who dare to fail miserably can achieve greatly",
"The opposite of love is not hate it’s indifference",
"When life gives you lemons make lemonade",
"Never let the fear of striking out keep you from playing the game",
"Life is like a box of chocolates You never know what you’re going to get",
"He that falls in love with himself will have no rivals",
"Life is ten percent what happens to you and ninety percent how you respond to it",
"Practice makes perfect",
"Dream big and dare to fail",
"A great man is always willing to be little",
"That’s one small step for a man one giant leap for mankind",
"Every man is guilty of all the good he did not do"
];
